### ISSUE TITLE
'near' keyword apparently does not support positioning near other objects, only static positions

### ISSUE THREAD

**Issue by bonesmoses** [terrastruct/d2#1097]
Documentation suggests otherwise, but this code produces an error:

```yaml
top_thing: Look at me

notes: blablabla {
  shape: text
  near: top_thing
}
```

This is the error from a d2 compile:

```
err: failed to compile: Object "notes" has "near" set to another object, but layout engine "elk" only supports constant values for "near".
```

Version according to `d2 version` is `v0.2.5-HEAD`. This is somewhat odd, as install was done with `go install oss.terrastruct.com/d2@latest` and the current latest is v0.2.6.
