### ISSUE TITLE
Install.sh script not working on Windows Server 2022

### ISSUE THREAD

**Issue by mech-a** [terrastruct/d2#1551]
I tried to install d2 in a Github Action using the underlying OS `windows-latest` which is Windows Server 2022. To do so, I tried the `install.sh` script but got an error. I think it might be a quoting issue, image below.
![image](https://github.com/terrastruct/d2/assets/11798509/7b00c264-c255-4ddc-879f-6feaa8a86825)

**Comment by nhooyr** [comment]
Looks like on line 3, the space has to be escaped?

**Comment by alixander** [comment]
must be that

**Comment by danieleades** [comment]
i'm also seeing an issue installing d2 in a windows-latest github environment using the script:

```
Run curl -fsSL https://d2lang.com/install.sh | sh -s --
  curl -fsSL https://d[2](https://github.com/danieleades/mdbook-d2/actions/runs/10226545157/job/28296923263?pr=75#step:4:2)lang.com/install.sh | sh -s --
  echo "$(which d2)" >> $GITHUB_PATH
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    CARGO_HOME: C:\Users\runneradmin/.cargo
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: always
/* installing d2-latest */
log: fetching info on latest version of terrastruct/d2
exec: curl -fL -#o /tmp/tmp.DubytO[3](https://github.com/danieleades/mdbook-d2/actions/runs/10226545157/job/28296923263?pr=75#step:4:3)eb9/1dbe89ead6ec8e52/release-info.json.inprogress -C- -H 'Accept: application/json' https://api.github.com/repos/terrastruct/d2/releases/latest
#=#=#                                                                          

exec: mv /tmp/tmp.DubytO3eb9/1dbe89ead6ec8e52/release-info.json.inprogress /tmp/tmp.DubytO3eb9/1dbe89ead6ec8e52/release-info.json
log: installing standalone release d2-v0.6.6-windows-amd6[4](https://github.com/danieleades/mdbook-d2/actions/runs/10226545157/job/28296923263?pr=75#step:4:4).tar.gz from github
exec: cat "$RELEASE_INFO" | grep -n "$ARCHIVE" | cut -d: -f1 | head -n1
exec: sed -n $((asset_line-3))p "$RELEASE_INFO" | sed "s/^.*: \"\(.*\)\",$/\1/g"
exec: curl -fL -#o ~/.cache/d2/release/d2-v0.6.6-windows-amd64.tar.gz.inprogress -C- -H 'Accept: application/octet-stream' https://api.github.com/repos/terrastruct/d2/releases/assets/1833731[5](https://github.com/danieleades/mdbook-d2/actions/runs/10226545157/job/28296923263?pr=75#step:4:5)7
#=#=#                                                                          

#####################################                                     52.3%
######################################################################## 100.0%
exec: mv ~/.cache/d2/release/d2-v0.[6](https://github.com/danieleades/mdbook-d2/actions/runs/10226545157/job/28296923263?pr=75#step:4:6).6-windows-amd64.tar.gz.inprogress ~/.cache/d2/release/d2-v0.6.6-windows-amd64.tar.gz
exec: mkdir -p '/usr/local/lib/d2'
exec: tar -C /usr/local/lib/d2 -xzf ~/.cache/d2/release/d2-v0.6.6-windows-amd64.tar.gz
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
exec: sh -c 'cd "/usr/local/lib/d2/d2-v0.6.6" && make install PREFIX="/usr/local"'
sh: C:\Program: No such file or directory
make: *** [Makefile:11: install] Error 12[7](https://github.com/danieleades/mdbook-d2/actions/runs/10226545157/job/28296923263?pr=75#step:4:7)
/usr/bin/which: no d2 in (/c/Program Files/PowerShell/7:/c/Program Files/MongoDB/Server/5.0/bin:/c/aliyun-cli:/c/vcpkg:/c/Program Files (x[8](https://github.com/danieleades/mdbook-d2/actions/runs/10226545157/job/28296923263?pr=75#step:4:8)6)/NSIS:/c/tools/zstd:/c/Program Files/Mercurial:/c/hostedtoolcache/windows/stack/3.1.1/x64:/c/cabal/bin:/c/ghcup/bin:/c/mingw64/bin:/c/Program Files/dotnet:/c/Program Files/MySQL/MySQL Server 8.0/bin:/c/Program Files/R/R-4.4.1/bin/x64:/c/SeleniumWebDrivers/GeckoDriver:/c/SeleniumWebDrivers/EdgeDriver:/c/SeleniumWebDrivers/ChromeDriver:/c/Program Files (x86)/sbt/bin:/c/Program Files (x86)/GitHub CLI:/bin:/c/Program Files (x86)/pipx_bin:/c/npm/prefix:/c/hostedtoolcache/windows/go/1.21.12/x64/bin:/c/hostedtoolcache/windows/Python/3.[9](https://github.com/danieleades/mdbook-d2/actions/runs/10226545157/job/28296923263?pr=75#step:4:10).13/x64/Scripts:/c/hostedtoolcache/windows/Python/3.9.13/x64:/c/hostedtoolcache/windows/Ruby/3.0.7/x64/bin:/c/Program Files/OpenSSL/bin:/c/tools/kotlinc/bin:/c/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/8.0.422-5/x64/bin:/c/Program Files/ImageMagick-7.1.1-Q16-HDRI:/c/Program Files/Microsoft SDKs/Azure/CLI2/wbin:/c/ProgramData/kind:/c/ProgramData/docker-compose:/c/ProgramData/Chocolatey/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/dotnet:/c/Program Files/PowerShell/7:/c/Program Files/Microsoft/Web Platform Installer:/c/Program Files/TortoiseSVN/bin:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files/Microsoft SQL Server/150/Tools/Binn:/c/Program Files (x86)/Windows Kits/[10](https://github.com/danieleades/mdbook-d2/actions/runs/10226545157/job/28296923263?pr=75#step:4:11)/Windows Performance Toolkit:/c/Program Files (x86)/WiX Toolset v3.14/bin:/c/Program Files/Microsoft SQL Server/130/DTS/Binn:/c/Program Files/Microsoft SQL Server/140/DTS/Binn:/c/Program Files/Microsoft SQL Server/150/DTS/Binn:/c/Program Files/Microsoft SQL Server/160/DTS/Binn:/c/Strawberry/c/bin:/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/ProgramData/chocolatey/lib/pulumi/tools/Pulumi/bin:/c/Program Files/CMake/bin:/c/ProgramData/chocolatey/lib/maven/apache-maven-3.8.7/bin:/c/Program Files/Microsoft Service Fabric/bin/Fabric/Fabric.Code:/c/Program Files/Microsoft SDKs/Service Fabric/Tools/ServiceFabricLocalClusterManager:/c/Program Files/nodejs:/cmd:/mingw64/bin:/usr/bin:/c/Program Files/GitHub CLI:/c/tools/php:/c/Program Files (x86)/sbt/bin:/c/Program Files/Amazon/AWSCLIV2:/c/Program Files/Amazon/SessionManagerPlugin/bin:/c/Program Files/Amazon/AWSSAMCLI/bin:/c/Program Files/Microsoft SQL Server/[13](https://github.com/danieleades/mdbook-d2/actions/runs/10226545157/job/28296923263?pr=75#step:4:14)0/Tools/Binn:/c/Program Files/LLVM/bin:/c/Users/runneradmin/.dotnet/tools:/c/Users/runneradmin/.cargo/bin:/c/Users/runneradmin/AppData/Local/Microsoft/WindowsApps)
```

**Comment by pawamoy** [comment]
Same here.

```
Run curl -fsSL https://d2lang.com/install.sh | sh -s --
  curl -fsSL https://d2lang.com/install.sh | sh -s --
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8
    PYTHONIOENCODING: UTF-8
    PYTHONWARNDEFAULTENCODING: 1
    PYTHON_VERSIONS: 
/* installing d2-latest */
log: fetching latest version of terrastruct/d2
log: detected latest version: v0.7.1
log: installing standalone release d2-v0.7.1-windows-amd64.tar.gz from github
exec: curl -fL -#o ~/.cache/d2/release/d2-v0.7.1-windows-amd64.tar.gz.inprogress -C- -H 'Accept: application/octet-stream' https://github.com/terrastruct/d2/releases/download/v0.7.1/d2-v0.7.1-windows-amd64.tar.gz

#=#=#                                                                          
##O#-#                                                                         
####################################################################      94.7%
######################################################################## 100.0%
exec: mv ~/.cache/d2/release/d2-v0.7.1-windows-amd64.tar.gz.inprogress ~/.cache/d2/release/d2-v0.7.1-windows-amd64.tar.gz
exec: mkdir -p '/usr/local/lib/d2'
exec: tar -C /usr/local/lib/d2 -xzf ~/.cache/d2/release/d2-v0.7.1-windows-amd64.tar.gz
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
exec: sh -c 'cd "/usr/local/lib/d2/d2-v0.7.1" && make install PREFIX="/usr/local"'
sh: C:\Program: No such file or directory
make: *** [Makefile:11: install] Error 127
```
