### ISSUE TITLE
proposal: style classes

### ISSUE THREAD

**Issue by hofq** [terrastruct/d2#770]
For easy styling i would like to use some kind of style classes. That could look like that (but it should not)
```yml
Group : {
  item: "Iteam"
  item.style: !422
  item2: "Item 2"
  item2.style: !422
}
!422 {
   font-size: 23;
   icon: ./assets/display.png
}
```
Would be nice to have something like that implemented in upcoming versions
